[DEBUG ==> api.py:389] 2019-10-16 06:49:32,001 >> main calculation start
[ERROR ==> api.py:517] 2019-10-16 06:49:32,006 >> Error occured, name 'soleEq_dict' is not defined
